import { Product, Seller, Broadcast, BroadcastChannel } from './store';

export const mockSellers: Seller[] = [
  {
    id: 's1',
    name: 'Wahid Fabric House',
    nameBn: 'ওয়াহিদ ফ্যাব্রিক হাউস',
    logo: 'https://api.dicebear.com/7.x/initials/svg?seed=WFH&backgroundColor=a84a3a',
    description: 'Fabric & Yarn Specialist',
    descriptionBn: 'ফ্যাব্রিক ও ইয়ার্ন বিশেষজ্ঞ',
    followers: 1260,
    productCount: 0,
    broadcastCount: 0,
    verified: true,
    categories: ['fabric', 'yarn'],
    banner: 'https://images.unsplash.com/photo-1588544622467-6df9eef29c7a',
  },
  {
    id: 's2',
    name: 'Zamee Yarn House',
    nameBn: 'জামী ইয়ার্ন হাউস',
    logo: 'https://api.dicebear.com/7.x/initials/svg?seed=ZYH&backgroundColor=a6a47a',
    description: 'Premium Yarn Supplier',
    descriptionBn: 'উচ্চমানের সুতা সরবরাহকর্তা',
    followers: 980,
    productCount: 0,
    broadcastCount: 0,
    verified: true,
    categories: ['yarn'],
    banner: 'https://images.unsplash.com/photo-1746737198845-e1e74bea786e',
  },
  {
    id: 's3',
    name: 'Rafeen Jute Corner',
    nameBn: 'রাফিন জুট কর্নার',
    logo: 'https://api.dicebear.com/7.x/initials/svg?seed=RJC&backgroundColor=8b7355',
    description: 'Natural Jute Fiber Supplier',
    descriptionBn: 'প্রাকৃতিক জুট ফাইবার সরবরাহকারী',
    followers: 560,
    productCount: 0,
    broadcastCount: 0,
    verified: true,
    categories: ['jute'],
    banner: 'https://images.unsplash.com/photo-1742301507306-196726872f33',
  },
  {
    id: 's4',
    name: 'ABC Leather LTD',
    nameBn: 'এবিসি লেদার লিমিটেড',
    logo: 'https://api.dicebear.com/7.x/initials/svg?seed=ABL&backgroundColor=5a4a3a',
    description: 'Leather & High-end Fabric',
    descriptionBn: 'লেদার ও হাই-এন্ড ফ্যাব্রিক',
    followers: 430,
    productCount: 0,
    broadcastCount: 0,
    verified: true,
    categories: ['leather', 'fabric'],
    banner: 'https://images.unsplash.com/photo-1601241773118-9e67091e199e',
  },
  {
    id: 's5',
    name: 'Russel Fiber House',
    nameBn: 'রাসেল ফাইবার হাউস',
    logo: 'https://api.dicebear.com/7.x/initials/svg?seed=RFH&backgroundColor=9a9a7a',
    description: 'Fiber & Blended Fabric',
    descriptionBn: 'ফাইবার ও মিশ্র ফ্যাব্রিক',
    followers: 210,
    productCount: 0,
    broadcastCount: 0,
    verified: false,
    categories: ['fiber', 'fabric'],
    banner: 'https://images.unsplash.com/photo-1666112514123-b3735b66aee3',
  },
];

export const mockProducts: Product[] = [
  {
    id: 'p1',
    sellerId: 's1',
    title: 'Denim Twill Fabric – 12oz Indigo',
    titleBn: 'ডেনিম টুইল ফেব্রিক – ১২ আউন্স ইন্ডিগো',
    price: 450,
    moq: '500 yards',
    blend: '98% Cotton, 2% Elastane',
    category: 'fabric',
    image: 'https://images.unsplash.com/photo-1588544622467-6df9eef29c7a?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxkZW5pbSUyMGplYW5zJTIwZmFicmljfGVufDF8fHx8MTc2MTY4NTk0OHww&ixlib=rb-4.1.0&q=80&w=1080',
    description: 'Premium denim twill fabric perfect for jeans manufacturing',
    descriptionBn: 'জিন্স তৈরির জন্য উপযুক্ত প্রিমিয়াম ডেনিম টুইল ফেব্রিক',
  },
  {
    id: 'p2',
    sellerId: 's4',
    title: 'Cotton Rib Fabric – Stretch Type',
    titleBn: 'কটন রিব ফেব্রিক – স্ট্রেচ টাইপ',
    price: 320,
    moq: '300 yards',
    blend: '95% Cotton, 5% Spandex',
    category: 'fabric',
    image: 'https://images.unsplash.com/photo-1601241773118-9e67091e199e?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxjb3R0b24lMjBzdHJldGNoJTIwZmFicmljfGVufDF8fHx8MTc2MTY5MTY2Mnww&ixlib=rb-4.1.0&q=80&w=1080',
    description: 'Soft stretch cotton rib fabric for t-shirts and activewear',
    descriptionBn: 'টি-শার্ট এবং অ্যাক্টিভওয়্যারের জন্য নরম স্ট্রেচ কটন রিব ফেব্রিক',
  },
  {
    id: 'p3',
    sellerId: 's1',
    title: 'Floral Pattern Printed Fabric',
    titleBn: 'ফুলের প্যাটার্ন প্রিন্টেড ফেব্রিক',
    price: 280,
    moq: '200 yards',
    blend: '100% Polyester',
    category: 'fabric',
    image: 'https://images.unsplash.com/photo-1761516126149-b570f4e8c899?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxmbG9yYWwlMjBwcmludGVkJTIwZmFicmljfGVufDF8fHx8MTc2MTY4NTk0OXww&ixlib=rb-4.1.0&q=80&w=1080',
    description: 'Beautiful floral printed fabric for ethnic and casual wear',
    descriptionBn: 'জাতিগত এবং নৈমিত্তিক পোশাকের জন্য সুন্দর ফুলের প্রিন্ট ফেব্রিক',
  },
  {
    id: 'p4',
    sellerId: 's3',
    title: 'Natural Jute Fiber – Grade A',
    titleBn: 'প্রাকৃতিক পাট ফাইবার – গ্রেড এ',
    price: 180,
    moq: '1000 kg',
    blend: '100% Natural Jute',
    category: 'jute',
    image: 'https://images.unsplash.com/photo-1742301507306-196726872f33?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxqdXRlJTIwZmliZXIlMjBjbG9zZSUyMHVwfGVufDF8fHx8MTc2MTY5NjI4OHww&ixlib=rb-4.1.0&q=80&w=1080',
    description: 'Premium grade natural jute fiber for eco-friendly products',
    descriptionBn: 'পরিবেশ বান্ধব পণ্যের জন্য প্রিমিয়াম গ্রেডের প্রাকৃতিক পাট ফাইবার',
  },
  {
    id: 'p5',
    sellerId: 's5',
    title: 'Polyester Viscose Fabric – PV Mix',
    titleBn: 'পলিয়েস্টার ভিসকোস ফেব্রিক – পিভি মিক্স',
    price: 350,
    moq: '400 yards',
    blend: '65% Polyester, 35% Viscose',
    category: 'fabric',
    image: 'https://images.unsplash.com/photo-1666112514123-b3735b66aee3?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxwb2x5ZXN0ZXIlMjBmYWJyaWMlMjByb2xsfGVufDF8fHx8MTc2MTY5MzUxNHww&ixlib=rb-4.1.0&q=80&w=1080',
    description: 'Breathable PV blend fabric for formal and business wear',
    descriptionBn: 'ফর্মাল এবং ব্যবসায়িক পোশাকের জন্য শ্বাসপ্রশ্বাসযোগ্য পিভি মিশ্রণ ফেব্রিক',
  },
  {
    id: 'p6',
    sellerId: 's2',
    title: 'Slub Yarn – 40s',
    titleBn: 'স্লাব সুতা – ৪০এস',
    price: 420,
    moq: '500 kg',
    blend: '100% Cotton',
    category: 'yarn',
    image: 'https://images.unsplash.com/photo-1746737198845-e1e74bea786e?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHx5YXJuJTIwcm9sbCUyMHRleHRpbGV8ZW58MXx8fHwxNzYxNjkyMjY2fDA&ixlib=rb-4.1.0&q=80&w=1080',
    description: 'High-quality slub yarn with unique texture for premium fabrics',
    descriptionBn: 'প্রিমিয়াম ফেব্রিকের জন্য অনন্য টেক্সচার সহ উচ্চমানের স্লাব সুতা',
  },
  {
    id: 'p7',
    sellerId: 's2',
    title: 'Viscose Melange Yarn – 28s',
    titleBn: 'ভিসকোস মেলাঞ্জ সুতা – ২৮এস',
    price: 480,
    moq: '400 kg',
    blend: '70% Viscose, 30% Cotton',
    category: 'yarn',
    image: 'https://images.unsplash.com/photo-1600916429132-8353efb090b5?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHx2aXNjb3NlJTIweWFybiUyMGNvbmV8ZW58MXx8fHwxNzYxNjk2Mjg4fDA&ixlib=rb-4.1.0&q=80&w=1080',
    description: 'Soft melange yarn with excellent color blending properties',
    descriptionBn: 'চমৎকার রঙ মিশ্রণ বৈশিষ্ট্য সহ নরম মেলাঞ্জ সুতা',
  },
  {
    id: 'p8',
    sellerId: 's4',
    title: 'Organic Cotton Blend Fabric',
    titleBn: 'অর্গানিক কটন ব্লেন্ড ফেব্রিক',
    price: 380,
    moq: '350 yards',
    blend: '90% Organic Cotton, 10% Bamboo',
    category: 'fabric',
    image: 'https://images.unsplash.com/photo-1603873932226-5d1d21826bb9?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxvcmdhbmljJTIwY290dG9uJTIwZmFicmljfGVufDF8fHx8MTc2MTY2MDY4N3ww&ixlib=rb-4.1.0&q=80&w=1080',
    description: 'Eco-friendly organic cotton blend for sustainable fashion',
    descriptionBn: 'টেকসই ফ্যাশনের জন্য পরিবেশ বান্ধব জৈব তুলা মিশ্রণ',
  },
];

// Broadcast Channels - Telegram-style channels for each seller
export const mockBroadcastChannels: BroadcastChannel[] = [
  {
    id: 'bc1',
    sellerId: 's1',
    name: 'Wahid Fabric Updates',
    nameBn: 'ওয়াহিদ ফ্যাব্রিক আপডেট',
    description: 'Get the latest updates on premium fabrics and exclusive deals',
    descriptionBn: 'প্রিমিয়াম ফ্যাব্রিক এবং এক্সক্লুসিভ ডিলের সর্বশেষ আপডেট পান',
    avatar: 'https://api.dicebear.com/7.x/initials/svg?seed=WFH&backgroundColor=a84a3a',
    subscribers: [],
    createdAt: Date.now() - 86400000 * 30, // 30 days ago
    isPremiumOnly: false,
    messageCount: 0,
    settings: {
      notificationsEnabled: true,
      allowComments: false,
      showSubscriberCount: true,
    },
  },
  {
    id: 'bc2',
    sellerId: 's2',
    name: 'Zamee Yarn Announcements',
    nameBn: 'জামী ইয়ার্ন ঘোষণা',
    description: 'Premium yarn arrivals and special offers',
    descriptionBn: 'প্রিমিয়াম সুতা আগমন এবং বিশেষ অফার',
    avatar: 'https://api.dicebear.com/7.x/initials/svg?seed=ZYH&backgroundColor=a6a47a',
    subscribers: [],
    createdAt: Date.now() - 86400000 * 25,
    isPremiumOnly: false,
    messageCount: 0,
    settings: {
      notificationsEnabled: true,
      allowComments: false,
      showSubscriberCount: true,
    },
  },
  {
    id: 'bc3',
    sellerId: 's3',
    name: 'Rafeen Jute News',
    nameBn: 'রাফিন জুট নিউজ',
    description: 'Natural jute fiber updates and sustainability news',
    descriptionBn: 'প্রাকৃতিক পাট ফাইবার আপডেট এবং স্থায়িত্ব সংবাদ',
    avatar: 'https://api.dicebear.com/7.x/initials/svg?seed=RJC&backgroundColor=8b7355',
    subscribers: [],
    createdAt: Date.now() - 86400000 * 20,
    isPremiumOnly: false,
    messageCount: 0,
    settings: {
      notificationsEnabled: true,
      allowComments: false,
      showSubscriberCount: true,
    },
  },
  {
    id: 'bc4',
    sellerId: 's4',
    name: 'ABC Leather Exclusive',
    nameBn: 'এবিসি লেদার এক্সক্লুসিভ',
    description: 'Exclusive leather and premium fabric collections',
    descriptionBn: 'এক্সক্লুসিভ লেদার এবং প্রিমিয়াম ফ্যাব্রিক কালেকশন',
    avatar: 'https://api.dicebear.com/7.x/initials/svg?seed=ABL&backgroundColor=5a4a3a',
    subscribers: [],
    createdAt: Date.now() - 86400000 * 15,
    isPremiumOnly: true, // Premium only channel
    messageCount: 0,
    settings: {
      notificationsEnabled: true,
      allowComments: false,
      showSubscriberCount: false,
    },
  },
  {
    id: 'bc5',
    sellerId: 's5',
    name: 'Russel Fiber Channel',
    nameBn: 'রাসেল ফাইবার চ্যানেল',
    description: 'Fiber and blended fabric announcements',
    descriptionBn: 'ফাইবার এবং মিশ্র ফ্যাব্রিক ঘোষণা',
    avatar: 'https://api.dicebear.com/7.x/initials/svg?seed=RFH&backgroundColor=9a9a7a',
    subscribers: [],
    createdAt: Date.now() - 86400000 * 10,
    isPremiumOnly: false,
    messageCount: 0,
    settings: {
      notificationsEnabled: true,
      allowComments: false,
      showSubscriberCount: true,
    },
  },
];

// Broadcast Messages - Individual messages in channels
export const mockBroadcasts: Broadcast[] = [
  {
    id: 'b1',
    channelId: 'bc1',
    sellerId: 's1',
    content: '🎉 New Collection Alert! Premium denim fabrics now available. Limited stock - order now!',
    productId: 'p1',
    timestamp: Date.now() - 3600000,
    views: [],
    reactions: [],
    forwards: 0,
    isPinned: false,
  },
  {
    id: 'b2',
    channelId: 'bc2',
    sellerId: 's2',
    content: 'Quality yarn shipment arriving next week. Pre-book your orders for best prices! 📦',
    productId: 'p6',
    timestamp: Date.now() - 7200000,
    views: [],
    reactions: [],
    forwards: 0,
    isPinned: false,
  },
  {
    id: 'b3',
    channelId: 'bc3',
    sellerId: 's3',
    content: '♻️ Eco-friendly jute fiber now certified organic. Perfect for sustainable brands.',
    timestamp: Date.now() - 10800000,
    views: [],
    reactions: [],
    forwards: 0,
    isPinned: true, // Pinned message
  },
  {
    id: 'b4',
    channelId: 'bc4',
    sellerId: 's4',
    content: '🔥 Flash Sale: 15% off on all cotton fabrics this week only!',
    productId: 'p2',
    timestamp: Date.now() - 14400000,
    views: [],
    reactions: [],
    forwards: 0,
    isPinned: false,
  },
  {
    id: 'b5',
    channelId: 'bc1',
    sellerId: 's1',
    content: 'New floral print collection perfect for the upcoming season. Check out our latest designs! 🌸',
    productId: 'p3',
    timestamp: Date.now() - 18000000,
    views: [],
    reactions: [],
    forwards: 0,
    isPinned: false,
  },
];
